[tool.poetry]
name = "pyserde_bench"
version = "0.1.0"
description = "Benchmark package for pyserde"
authors = ["yukinarit <yukinarit84@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7.0"
click = "*"
pyserde = {path = "../"}

[tool.poetry.dev-dependencies]
# dacite = "*"
# mashumaro = "^2.11.0"
# marshmallow = "~=3.2"
# attrs = "*"
# cattrs = "*"
# seaborn = "*"
# matplotlib = "*"
# numpy = "*"
